/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package voronoigame.view;

import voronoigame.controller.GameController;
import voronoigame.model.GameState;

/**
 *
 * @author Maurice
 */
public class GamePanel extends ContentPanel {
    
    private GameController gameController;
    
    GamePanel(GameState gameState, MainView parent) {
        super(parent);
        initComponents();
        this.setupGame(gameState);
    }

    private void setupGame(GameState gameState) {
        this.voronoiPanel.setGameState(gameState);
        this.gameController = new GameController(gameState);
        this.voronoiPanel.addMouseListener(this.gameController);
        this.voronoiPanel.addMouseMotionListener(this.gameController);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuContainer = new javax.swing.JPanel();
        stopButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        voronoiPanel = new voronoigame.view.voronoi.VoronoiPanel();

        setLayout(new java.awt.BorderLayout());

        menuContainer.setMaximumSize(new java.awt.Dimension(32767, 100));
        menuContainer.setLayout(new java.awt.GridLayout());

        stopButton.setText("stop");
        menuContainer.add(stopButton);

        nextButton.setText("next");
        nextButton.setActionCommand("next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        menuContainer.add(nextButton);

        add(menuContainer, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout voronoiPanelLayout = new javax.swing.GroupLayout(voronoiPanel);
        voronoiPanel.setLayout(voronoiPanelLayout);
        voronoiPanelLayout.setHorizontalGroup(
            voronoiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        voronoiPanelLayout.setVerticalGroup(
            voronoiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        add(voronoiPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        
    }//GEN-LAST:event_nextButtonActionPerformed

    @Override
    protected void onPanelAdded() { }

    @Override
    protected void onPanelRemoved() { }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel menuContainer;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton stopButton;
    private voronoigame.view.voronoi.VoronoiPanel voronoiPanel;
    // End of variables declaration//GEN-END:variables

    
}
