/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package voronoigame.view;

/**
 *
 * @author Guus van Lankveld
 */
public class MainView extends javax.swing.JFrame {

    private VoronoiPanel voronoiPanel;

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * Removes the VoronoiPanel from this frame.
     *
     * @return The removed VoronoiPanel, or null if there was none.
     */
    public VoronoiPanel removeVoronoiPanel() {
        if (this.voronoiPanel != null) {
            this.pnVoronoiContainer.remove(this.voronoiPanel);
            this.voronoiPanel.removeGameController();
            this.voronoiPanel.setVisible(false);
            VoronoiPanel removed = this.voronoiPanel;
            this.voronoiPanel = null;
            return removed;
        } else {
            return null;
        }
    }

    /**
     * Uses the given VoronoiPanel as the VoronoiPanel for this frame. This will
     * remove the existing VoronoiPanel if applicable.
     *
     * @param voronoiPanel The VoronoiPanel to use.
     */
    public void setVoronoiPanel(VoronoiPanel voronoiPanel) {

        // If there is an existing panel, remove it
        this.removeVoronoiPanel();

        this.voronoiPanel = voronoiPanel;
        this.pnVoronoiContainer.add(this.voronoiPanel);
        this.voronoiPanel.updateSize();
    }

    public VoronoiPanel getVoronoiPanel() {
        return this.voronoiPanel;
    }

    public boolean hasVoronoiPanel() {
        return this.voronoiPanel != null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pnVoronoiContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout pnVoronoiContainerLayout = new javax.swing.GroupLayout(pnVoronoiContainer);
        pnVoronoiContainer.setLayout(pnVoronoiContainerLayout);
        pnVoronoiContainerLayout.setHorizontalGroup(
            pnVoronoiContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        pnVoronoiContainerLayout.setVerticalGroup(
            pnVoronoiContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnVoronoiContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnVoronoiContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnVoronoiContainer;
    // End of variables declaration//GEN-END:variables

}
